# Generated by Django 4.2.23 on 2025-08-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_bw_page', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('price_per_color_page', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('binding_cost', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('payment_policy', models.CharField(choices=[('FULL_ONLY', 'Full Payment Only'), ('ADVANCE_ALLOWED', 'Advance Payment Allowed')], default='FULL_ONLY', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('ADVANCE_PAID', 'Advance Paid'), ('FULL_PAID', 'Full Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('is_emergency', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='print_documents/')),
                ('total_pages', models.IntegerField(default=0)),
                ('num_copies', models.IntegerField(default=1)),
                ('is_color', models.BooleanField(default=False)),
                ('color_pages_info', models.TextField(blank=True, null=True)),
                ('needs_binding', models.BooleanField(default=False)),
                ('item_estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('is_printed_by_admin', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smartprint.printorder')),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='predefined_documents/')),
                ('total_pages', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
